account/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .forms import LoginForm



app_name = 'account'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html', form_class=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(template_name='account/index.html'), name='logout'),
]

chat/urls.py
from django.urls import path
# from rest_framework.routers import DefaultRouter

from . import views

app_name = 'chat'
# router = DefaultRouter()
# router.register(r'api/create-room/<str:uuid>', views.ChatRoomViewSet, basename='chat-room-api')
# urlpatterns = router.urls
# [
#     path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
# ]

urlpatterns = [
    path('api/create-room/<str:uuid>/', views.create_room, name='create-room'),
    path('chat-admin/', views.admin, name='admin'),
    path('chat-admin/add-user/', views.add_user, name='add_user'),
    path('chat-admin/<uuid:uuid>/', views.get_user, name='get_user '),
    path('chat-admin/<str:uuid>/delete', views.room_delete, name='delete_room'),
    
    path('chat-admin/users/<str:uuid>/', views.room, name='room'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('team/', views.team, name='team'),
    path('services/', views.services, name='services'),
    path('why/', views.why, name='why'),
    path('profile/', views.profile, name='profile'),
]

orion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls'), name='chat.urls'),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

def team(request):
    return render(request, 'core/team.html')

def services(request):
    return render(request, 'core/services.html')

def why(request):
    return render(request, 'core/why.html')

def profile(request):
    return render(request, 'core/profile.html')

core/templates/core/about.html
{% load static %}
<!DOCTYPE html>
  <html>
  
  <head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">
  
    <title> Orion </title>
  
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  
    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
  
    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  
    <!-- font awesome style -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
  
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <!-- responsive style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  
  </head>
  
  <body class="sub_page">
  
    <div class="hero_area">
  
      <div class="hero_bg_box">
        <div class="bg_img_box">
          <img src="images/hero-bg.png" alt="">
        </div>
      </div>
  
      <!-- header section strats -->
      <header class="header_section">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="{% url 'core:index' %}">
              <img style="width:300px" src="{% static 'images/logo2.svg' %}" alt="">
            </a>
  
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""> </span>
            </button>
  
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:about' %}"> About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:services' %}">Services</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:why' %}">Why Us</a>
                </li>
             
                {% if request.user.is_superuser %}
                <li class="nav-item">
                  
                      <a href="{% url 'chat:admin' %}" class="nav-link">Admin</a>
                  
                </li>
                {% endif %}
  
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                      <a href="{% url 'core:profile' %}" class="nav-link">Profile</a>
                    </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                          <a href="{% url 'account:logout' %}" class="nav-link">logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                        
                          <a class="nav-link" href="{% url 'account:login' %}"> <i class="fa fa-user" aria-hidden="true"></i> Login</a>
                          
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'chat:add_user' %}"><i class="fa fa-user" aria-hidden="true"></i>Register</a>
                          
                        </li>
                        {% endif %}
                 
               
               
                <form class="form-inline">
                  <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                    <i class="fa fa-search" aria-hidden="true"></i>
                  </button>
                </form>
              </ul>
            </div>
          </nav>
        </div>
      </header>
      <!-- end header section -->
    </div>
  <!-- about section -->

  <section class="about_section layout_padding">
    <div class="container  ">
      <div class="heading_container heading_center">
        <h2>
          About <span>Us</span>
        </h2>
        <p>
          Investing Now available to everyone.
        </p>
      </div>
      <div class="row">
        <div class="col-md-6 ">
          <div class="img-box">
            <img src="{% static 'images/Investment-PNG-Free-Image.png' %}" alt="">
          </div>
        </div>
        <div class="col-md-6">
          <div class="detail-box">
            <h3>
              We Are Orion
            </h3>
            <p>
              At Orion, we see investing differently. Today’s financial system is complex, exclusive and expensive - making it hard for the typical person to start investing. 
              So, we’re building a platform without digital walls and complex barriers. A platform that empowers you to see new possibilities for your money - and helps make them a reality.
            </p>
            <p>
              Orion was founded in 2014 in Vienna, Austria with the aim of making investing accessible for everyone. Our goals since day one was to reimagine what it means to invest, by making simple, easy-to-use financial products for everyone.

              Now, 8 years later, and with more than 700 team members and 4 million users, we're one of the most successful fintechs in Europe. With a PSD2 payment service provider licence and E-Money licence, state-of-the-art security and streamlined user experience, we make it possible for both first-time investors and seasoned experts to invest in what they believe in. 

              Our user-friendly, trade-everything platform empowers you to invest in the stocks, cryptocurrencies, metals, commodities and crypto indices you want — with any amount of money.
            </p>
         
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->
  
    <!-- info section -->
  
    <!-- info section -->

  <section class="info_section layout_padding2">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 info_col">
          <div class="info_contact">
            <h4>
              Address
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +1(615) 398-0512
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  1joncruise@gmail.com
                </span>
              </a>
            </div>
          </div>
          <div class="info_social">
            <a href="#">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="#">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="#">
              <i class="fa fa-linkedin" aria-hidden="true"></i>
            </a>
            <a href="#">
              <i class="fa fa-instagram" aria-hidden="true"></i>
            </a>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 info_col">
          <div class="info_detail">
            <h4>
              Info
            </h4>
            <p>
              Orion is a digital assets platform based in Vienna, Austria. It was founded in 2014 has since grown to become one of the leading digital asset platforms in Europe. Orion is known for its user-friendly interface, wide range of supported cryptocurrencies, and various investment options
            </p>
          </div>
        </div>
        <div class="col-md-6 col-lg-2 mx-auto info_col">
          <div class="info_link_box">
            <h4>
              Links
            </h4>
            <div class="info_links">
              <a class="active" href="{% url 'core:index' %}">
                Home
              </a>
              <a class="" href="{% url 'core:about' %}">
                About
              </a>
              <a class="" href="{% url 'core:services' %}">
                Services
              </a>
              <a class="" href="{% url 'core:why' %}">
                Why Us
              </a>
              <a class="" href="{% url 'core:team' %}">
                Team
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 info_col ">
          <h4>
            Subscribe
          </h4>
          <form action="#">
            <input type="text" placeholder="Enter email" />
            <button type="submit">
              Subscribe
            </button>
          </form>
        </div>
      </div>
    </div>
  </section>
  
  
    <!-- jQery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- bootstrap js -->
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <!-- owl slider -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <!-- custom js -->
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
    </script>
    <!-- End Google Map -->
  
  </body>
  
  </html>

core/templates/core/base.html
{% load static %}

<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
    </head>

    <body>
        <div class="p-2">
            <nav class="p-6 bg-blue-950 text-white flex justify-between items-center rounded-xl">
                <a href="{% url 'core:index' %}" class="text-xl">Orion</a>

                <div class="flex items-center space-x-4">
                    <a href="{% url 'core:index' %}">Home</a>
                    <a href="{% url 'core:about' %}">About</a>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'chat:admin' %}" class="inline-block py-4 px-6 bg-blue-800 text-white rounded-xl">Admin</a>
                    {% endif %}
                </div>
            </nav>

            <main class="max-w-6xl mx-auto p-6">
                {% if messages %}
                    <div class="message mb-6 p-6 bg-gray-800 text-white rounded-xl">
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                {% block content %}
                {% endblock %}
            </main>
        </div>

        <footer class="py-12 px-6 bg-gray-800 text-white text-center text-xs">
            <p>Copyright (c) 2023 - Orion</p>
        </footer>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

core/templates/core/profile.html
{% load static %}
<!DOCTYPE html>
  <html>
  
  <head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">
  
    <title> Orion </title>
  
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  
    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
  
    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  
    <!-- font awesome style -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
  
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <!-- responsive style -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap');

    body {
        display: grid;
        place-items: center;
        background: #00204a
    }

    .card {
        color:#fff;
        width: 350px;
        border-radius: 10px;
        background: linear-gradient(145deg, #4040a9, #4c67c9);
        box-shadow:  20px 20px 60px #413ca0, 
                -20px -20px 60px #525dd8;
        border: none
    }

    .neo-button {
        width: 40px;
        height: 40px;
        outline: 0 !important;
        cursor: pointer;
        color: #fff;
        font-size: 15px;
        border: none;
        margin-right: 10px;
        border-radius: 50%;
    background: linear-gradient(145deg, #4440a9, #564cc9);
    box-shadow: inset 20px 20px 60px #3c57a0, 
                inset -20px -20px 60px #526dd8;
    }

    .num{
        
        color:#eee !important;
    }

    .line{
        color:#fff;
    }

    .neo-button:active {
    border-radius: 50%;
    background: #4747bc;
    box-shadow:  28px 28px 57px #3d4aa2, 
                -28px -28px 57px #5153d6;
    }

    .fa-facebook {
        color: #3b5998
    }

    .fa-linkedin {
        color: #0077b5
    }

    .fa-google {
        color: #dc4e41
    }

    .fa-youtube {
        color: #cd201f
    }

    .fa-twitter {
        color: #55acee
    }

    .profile_button{
        color:#fff;
        padding:10px; 
        border:none;
        outline:0 !important;
        border-radius: 50px;
        background: #4757bc;
        box-shadow:  28px 28px 57px #3f3da2, 
                -28px -28px 57px #5161d6;
        
    }
    </style>
  </head>
  
  <body class="sub_page">
  
    <div class="hero_area">
  
      <div class="hero_bg_box">
        <div class="bg_img_box">
          <img src="images/hero-bg.png" alt="">
        </div>
      </div>
  
      <!-- header section strats -->
      <header class="header_section">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="{% url 'core:index' %}">
              <img style="width:300px" src="{% static 'images/logo2.svg' %}" alt="">
            </a>
  
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""> </span>
            </button>
  
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:about' %}"> About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:services' %}">Services</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:why' %}">Why Us</a>
                </li>
             
                {% if request.user.is_superuser %}
                <li class="nav-item">
                  
                      <a href="{% url 'chat:admin' %}" class="nav-link">Admin</a>
                  
                </li>
                {% endif %}
  
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                      <a href="{% url 'core:profile' %}" class="nav-link">Profile</a>
                    </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                          <a href="{% url 'account:logout' %}" class="nav-link">logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                        
                          <a class="nav-link" href="{% url 'account:login' %}"> <i class="fa fa-user" aria-hidden="true"></i> Login</a>
                          
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'chat:add_user' %}"><i class="fa fa-user" aria-hidden="true"></i>Register</a>
                          
                        </li>
                        {% endif %}
                 
               
               
                <form class="form-inline">
                  <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                    <i class="fa fa-search" aria-hidden="true"></i>
                  </button>
                </form>
              </ul>
            </div>
          </nav>
        </div>
      </header>
      <!-- end header section -->
    </div>
  
    <!-- profile section -->
    <div style="margin-top:5%;"class="container d-flex justify-content-center">
        <div class="card p-3 py-4">
            <div class="text-center"> 
            {% comment %} <img src="https://i.imgur.com/stD0Q19.jpg" width="100" class="rounded-circle"> {% endcomment %}
                <h4 class="mt-2">{{request.user.name}}</h4>
                <span class="mt-1 clearfix">{{request.user.email}}</span>
                
                <div class="row mt-3 mb-3">
                
                  <div class="col-md-4 ">
                    <h6>Investment</h6>
                    <span class="num">{{request.user.amount}}</span>
                  </div>
                  <div class="col-md-4">
                  <h6>Profit</h6>
                    <span class="num">{{request.user.profit}}</span>
                  </div>
                  <div class="col-md-4">
                  <h6>Lose</h6>
                    <span class="num">{{request.user.loss}}</span>
                  </div>
                
                </div>
                
                <hr class="line">
                
                {% comment %} <small class="mt-4">I am an android developer working at google Inc at california,USA</small>
                  <div class="social-buttons mt-5"> 
                   <button class="neo-button"><i class="fa fa-facebook fa-1x"></i> </button> 
                   <button class="neo-button"><i class="fa fa-linkedin fa-1x"></i></button> 
                   <button class="neo-button"><i class="fa fa-google fa-1x"></i> </button> 
                   <button class="neo-button"><i class="fa fa-youtube fa-1x"></i> </button>
                   <button class="neo-button"><i class="fa fa-twitter fa-1x"></i> </button>
                  </div> {% endcomment %}
                  
                 <div class="profile mt-5">
                 
                 <button class="profile_button px-5">View details</button>
    
            </div>
                   
            </div>
        </div>
    </div>
  
    <!-- end profile section -->
    <!-- info section -->
  
 <!-- info section -->

 <section class="info_section layout_padding2">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-3 info_col">
        <div class="info_contact">
          <h4>
            Address
          </h4>
          <div class="contact_link_box">
            <a href="">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <span>
                Location
              </span>
            </a>
            <a href="">
              <i class="fa fa-phone" aria-hidden="true"></i>
              <span>
                Call +1(615) 398-0512
              </span>
            </a>
            <a href="">
              <i class="fa fa-envelope" aria-hidden="true"></i>
              <span>
                1joncruise@gmail.com
              </span>
            </a>
          </div>
        </div>
        <div class="info_social">
          <a href="#">
            <i class="fa fa-facebook" aria-hidden="true"></i>
          </a>
          <a href="#">
            <i class="fa fa-twitter" aria-hidden="true"></i>
          </a>
          <a href="#">
            <i class="fa fa-linkedin" aria-hidden="true"></i>
          </a>
          <a href="#">
            <i class="fa fa-instagram" aria-hidden="true"></i>
          </a>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 info_col">
        <div class="info_detail">
          <h4>
            Info
          </h4>
          <p>
            Orion is a digital assets platform based in Vienna, Austria. It was founded in 2014 has since grown to become one of the leading digital asset platforms in Europe. Orion is known for its user-friendly interface, wide range of supported cryptocurrencies, and various investment options
          </p>
        </div>
      </div>
      <div class="col-md-6 col-lg-2 mx-auto info_col">
        <div class="info_link_box">
          <h4>
            Links
          </h4>
          <div class="info_links">
            <a class="active" href="{% url 'core:index' %}">
              Home
            </a>
            <a class="" href="{% url 'core:about' %}">
              About
            </a>
            <a class="" href="{% url 'core:services' %}">
              Services
            </a>
            <a class="" href="{% url 'core:why' %}">
              Why Us
            </a>
            <a class="" href="{% url 'core:team' %}">
              Team
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 info_col ">
        <h4>
          Subscribe
        </h4>
        <form action="#">
          <input type="text" placeholder="Enter email" />
          <button type="submit">
            Subscribe
          </button>
        </form>
      </div>
    </div>
  </div>
</section>
    

  
    <!-- jQery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- bootstrap js -->
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <!-- owl slider -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <!-- custom js -->
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
    </script>
    <!-- End Google Map -->
  
  </body>
  
  </html>